name: Deploy by branch to Firebase Hosting

on:
  push:
    branches: [dev, staging, main]

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - branch: dev
            target: dev
          - branch: staging
            target: stg
          - branch: main
            target: prod
    if: github.ref_name == matrix.branch
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BINGO_ONLINE_231FD }}
          projectId: bingo-online-231fd
          target: ${{ matrix.target }}
          channelId: live
